spring:
  application:
    name: auth-service

server:
  port: 9100

eureka:
  client:
    service-url:
      defaultZone:
        http://eureka-server:8761/eureka

jwt:
  config:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey

jms:
  sender:
    broker-url: tcp://localhost:61616


