spring:
  application:
    name: auth-service

server:
  port: 9100

eureka:
  client:
    service-url:
      default-zone:
        http://localhost:8761/eureka

jwt:
  config:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 24*60*60
    secret: JwtSecretKey


